Some additions
sweirich/challenge pull request #4
Opened 2020-06-23 22:34 UTC by phadej

I got nerd-snippet by whether we can have better type for `step` question.

2020-06-23 23:12 UTC, phadej commented
Last commit is a puzzle for @RyanGlScott

2020-06-23 23:31 UTC, RyanGlScott commented
As you've already noted in the edit to your comment in https://github.com/sweirich/challenge/pull/4#issuecomment-648475236, I once tried to solve the puzzle of automating everything in `SubstScoped` [and failed](https://github.com/sweirich/challenge/issues/2#issuecomment-647707940). Perhaps you will have better luck?

2020-06-24 00:02 UTC, phadej commented
Oh no, *automating* is difficult when we don't even know what we want to be generated.

Yet with

```diff
diff --git a/debruijn/src/SubstScoped.hs b/debruijn/src/SubstScoped.hs
index afca123..335b733 100644
--- a/debruijn/src/SubstScoped.hs
+++ b/debruijn/src/SubstScoped.hs
@@ -20,9 +20,9 @@ data Idx :: Nat -> Type where
 -- We can lift Idx, but singletons cannot do that for us :/
 data SIdx (i :: Idx n) where
     SFZ :: SIdx 'FZ
-    SFS :: SIdx i -> SIdx ('FS i)
+    SFS :: SIdx (i :: Idx n) -> SIdx ('FS i :: Idx ('S n))
 
-type instance Sing = SIdx
+type instance Sing = SIdx :: Idx n -> Type
 
 instance SingI 'FZ where sing = SFZ
 instance SingI i => SingI ('FS i) where sing = SFS sing
@@ -66,14 +66,26 @@ instance C.Category (Sub a) where
     id = nilSub
     (.) = flip (:<>)
 
+data SSub (sub :: Sub a n m) where
+    SInc   :: forall m (sm :: Sing m). Sing m -> SSub ('Inc sm)
+    (:%<)  :: Sing a -> SSub sub -> SSub (a ':< sub)
+    (:%<>) :: SSub sub1 ->SSub sub2 ->SSub (sub1 ':<> sub2)
+
 -- | Identity substitution, leaves all variables alone
 nilSub :: Sub a n n 
 nilSub = Inc SZ
 
+type NilSub = 'Inc 'SZ :: Sub a n n
+
+sNilSub :: SSub NilSub
+sNilSub = SInc SZ
+
 -- | Increment, shifts all variables by one
 incSub :: Sub a n (S n)
 incSub = Inc (SS SZ)
 
+type IncSub = 'Inc ('SS 'SZ) :: Sub a n (S n)
+
 -- | Singleton, replace 0 with t, leave everything else alone
 singleSub :: a n -> Sub a (S n) n
 singleSub t = t :< nilSub
@@ -89,6 +101,14 @@ add :: Sing m -> Idx n -> Idx (Plus m n)
 add SZ x = x
 add (SS m) x = FS (add m x)
 
+type family Add (m :: Nat) (i :: Idx n) :: Idx (Plus m n) where
+    Add 'Z     x = x
+    Add ('S m) x = 'FS (Add m x)
+
+sAdd :: Sing m -> Sing i -> Sing (Add m i)
+sAdd SZ     x = x
+sAdd (SS m) x = SFS (sAdd m x)
+
 -- | Value of the index x in the substitution s
 applySub :: SubstDB a => Sub a n m -> Idx n -> a m
 applySub (Inc m)        x  = var (add m x)
```

only `SubstDB` and `applySub` (I consider `lift` easy after that) need promotion. There one need some defunctionalization term for `SubstDB` methods, but I think it is doable.

Here I chose (= the first thing I tried) is to avoid double promotion of singletons. It seems to work so far.

2020-06-24 11:41 UTC, RyanGlScott commented
Certainly, I have no doubt that you can manually promote and single everything in `SubstScoped` if you so chose. I have to imagine that will be quite painful, however. :)

2020-06-24 12:31 UTC, phadej commented
@RyanGlScott I got quite far, cannot give up at this point.

We have weird hobbies.

2020-06-24 12:55 UTC, sweirich requested changes
Thanks for the addition! This is fun.

Can you put this to a separate file, similar to Cps.hs and Typecheck.hs? I'd like to keep the main 'SimpleTyped' module short. (And maintain parity between it and the other versions (Poly/Simple/PolyTyped/...)

2020-06-24 12:58 UTC, sweirich reviewed
I've created a separate branch for experiments with singletons for Idx (i.e. adding type scopes).

2020-06-24 13:00 UTC, sweirich approved these changes

2020-06-24 13:17 UTC, sweirich commented on debruijn/src/SimpleTyped.hs
> +   -- i.e. recursive substitutions.
Awesome! I didn't realize that hereditary substitutions work with this interface too.

2020-06-24 13:22 UTC, sweirich commented on debruijn/src/SimpleTyped.hs
> +-- so we can define
did you mean to put "WHNF" at the end of this sentence?

2020-06-24 13:49 UTC, sweirich commented on debruijn/src/SimpleTyped.hs
> +      --
Thanks!  That example was indeed confused.  I've just updated the example to be parallel reduction (which doesn't necessarily produce a normal form in one step, but does demonstrate reduction under binders.)

2020-06-24 13:54 UTC, phadej commented
I split `Norm` things into own module. Also removed `Idx` changes from this branch.

2020-06-24 13:55 UTC, sweirich requested changes
Thanks.  Can you also move the by-hand singletons in SubstScoped to the other branch?  I don't want to give the impression that they are necessary for this example.

2020-06-24 13:56 UTC, phadej commented
> Thanks. Can you also move the by-hand singletons in SubstScoped to the other branch? I don't want to give the impression that they are necessary for this example.

That's done.

2020-06-24 13:57 UTC, sweirich approved these changes
Thanks!

2020-06-24 13:57 UTC, merged